# Generated by Django 3.0.5 on 2021-03-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210302_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('test_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=1)),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPointsTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('test_id', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestFileModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task/tests', verbose_name='Plik')),
                ('name', models.CharField(max_length=100, verbose_name='Wyświetlana nazwa testu')),
                ('has_been_chcecked', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField(verbose_name='Data rozpoczęcia testu')),
                ('date_end', models.DateTimeField(verbose_name='Data zakończenia testu')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='Grupa')),
            ],
        ),
    ]
