# Generated by Django 3.0.5 on 2020-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_zadania', models.IntegerField(primary_key=True, serialize=False)),
                ('temat', models.CharField(max_length=256)),
                ('deadline', models.DateTimeField()),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
    ]
