# Generated by Django 3.1.7 on 2021-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('content', models.TextField(default=None, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionXml',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
