# Generated by Django 3.1.7 on 2021-03-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Promela', '0001_initial'),
        ('upload', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionxml',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist'),
        ),
        migrations.AddField(
            model_name='questionpromela',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promela.teachertask'),
        ),
    ]
