# Generated by Django 3.1.7 on 2021-03-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210305_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default=None, max_length=100, verbose_name='Nazwa zadania')),
                ('max_points', models.IntegerField(default=0, verbose_name='Maksymalne punkty')),
                ('file', models.FileField(upload_to='task/promela/teacher_ltl', verbose_name='Plik')),
                ('date_end', models.DateTimeField(blank=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='0', max_length=100)),
                ('task_file', models.FileField(upload_to='task/promela/student_files', verbose_name='Plik')),
                ('output_file', models.FileField(upload_to='', verbose_name='Output')),
                ('points', models.IntegerField(default=0)),
                ('snumber', models.CharField(max_length=6)),
                ('group_id', models.CharField(default='0', max_length=100)),
                ('has_been_tested', models.BooleanField(default=False)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promela.teachertask')),
            ],
            options={
                'ordering': ('group_id', 'task_id'),
            },
        ),
    ]
