# Generated by Django 3.1.7 on 2021-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertask',
            name='task_content',
            field=models.TextField(default=None, max_length=500, verbose_name='Treść zadania'),
        ),
        migrations.AlterField(
            model_name='teachertask',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
