# Generated by Django 3.0.5 on 2020-05-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendedTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/SendedTasks/')),
            ],
        ),
    ]
