# Generated by Django 3.1.7 on 2021-03-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210305_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber1', models.CharField(max_length=6)),
                ('snumber2', models.CharField(max_length=6)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('plagiat', models.FloatField()),
                ('group_id', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ('-plagiat',),
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(default=None, max_length=200, verbose_name='Nazwa zadania')),
                ('tname', models.CharField(max_length=100)),
                ('task', models.FileField(upload_to='task/tasklist/', verbose_name='Plik')),
                ('date_end', models.DateTimeField(blank=True)),
                ('group_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsPoints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('number_task', models.CharField(max_length=3)),
                ('points', models.IntegerField(default=0)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist')),
            ],
            options={
                'ordering': ('taskid', 'snumber'),
            },
        ),
        migrations.CreateModel(
            name='SendedTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/sendedtasks/', verbose_name='Plik')),
                ('has_been_tested', models.BooleanField(default=False)),
                ('group', models.CharField(default='0', max_length=100)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist')),
            ],
            options={
                'ordering': ('group', 'taskid'),
            },
        ),
    ]
