# Generated by Django 3.1.1 on 2020-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('task', models.FileField(upload_to='task/TaskList/')),
            ],
        ),
    ]
