# Generated by Django 3.1.1 on 2020-09-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_tasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedtasks',
            name='task',
            field=models.FileField(upload_to='task/sendedtasks/'),
        ),
    ]
