# Generated by Django 3.1.6 on 2021-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('snumber', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Numer indeksu')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_username', models.DateTimeField(auto_now=True, verbose_name='last username')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('group', models.CharField(default=0, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=4)),
            ],
        ),
    ]
