# Generated by Django 3.1.5 on 2021-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(default=0, max_length=100, verbose_name='Grupa'),
        ),
    ]
